= About the Minnesota Agile Study Group

This group was founded at the http://advanceitmn.org/[May 2015 Advance-IT New Directions in IT Education conference] in Minnesota.  The initiating "pitch deck" is available on http://www.slideshare.net/alphas0ng/pitch-editagileed[Slideshare].

== Structure of The Agile Study Group
The founding members of The Agile Study Group are:

* Charles Betz, Digital Management Academy and University of St. Thomas
* Larry Gottschalk, Metro State University
* Firasat Khan, Metro State University and Director, Academic Initiatives, Advance-IT Minnesota
* Mary Mosman, Hennepin Technical College
* Jack Pope, North Hennepin Community College
* Rob Sleezer, Minnesota State University, Mankato

The Agile Study Group is not formally incorporated at this time and is run on the consensus of the founding members. Charles Betz is currently the Meetup.com organizer of record. Further evolution of governance is anticipated.

== General principles
The most troubling words heard in the Agile movement are: “You just don’t get Agile.”

This group is founded on a spirit of mutual respectful inquiry and on the premise that knowledge can be shared and communicated. It assumes that anyone, at any point in their career, can learn and change their worldview.

It is also based on the understanding that IT management and the education of its practitioners is itself a complex socio-technical system, in which interventions must be carefully considered, incrementally executed, and accurately measured. This is the true application of Agile theory and philosophy.


== Activities of the Agile Study Group

Activities this group is pursuing and considering include:

* Advocacy of public and private support for Agile educational programming in the mainstream Minnesota post-secondary systems
 * Research into local industry needs and educational practices
** Current state of IT education, with respect to Agile
** Current state of enterprise Agile adoption
** Current perceptions of IT education, from local Agile practitioners
* A monthly "book club" get-together to develop our mutual understanding of Agile theory and empirical evidence
* Reference curricula for educators and educational systems
* Collaborative development of simulations, lessons, and labs

* Research, papers and presentations

== Meetup

Face to face meetings are organized through the http://www.meetup.com/Agile-Study-Group/[Minnesota Agile Study Group Meetup]. Two books have been studied:

* http://www.amazon.com/Phoenix-Project-DevOps-Helping-Business/dp/0988262509/ref=sr_1_1?ie=UTF8&qid=1441330792&sr=8-1&keywords=phoenix+project&pebp=1441330794286&perid=02FVCTTQWX2FP17AE7MJ[The Phoenix Project], by Gene Kim, Kevin Behr, George Spafford

* http://www.amazon.com/Principles-Product-Development-Flow-Generation/dp/1935401009/ref=sr_1_1?ie=UTF8&qid=1441330813&sr=8-1&keywords=reinertsen&pebp=1441330815457&perid=0J863JC1ABM7QDCMR37C[The Principles of Product Development Flow], by Donald Reinertsen

Meetings are open to all interested parties: faculty, industry, students.
