= Devops Certificate Approach

== Questions

What is the target market for this class?

== Objectives

=== Hands on
DevOps fundamentals including its vision, culture, workflow, monitoring methods and tools. Students will take these concepts and see how they relate to automated and A/B testing and orient them towards the notion of release pipelines. Leading experts will share current methods and best practices in the field of continuous monitoring and deployment strategies.
Topics include:

* Concepts and vision of Dev and Ops to DevOps
* Release and deployment pipelines
* Automated testing
* A/B testing
* Production monitoring
* Common personas in the DevOps value stream
* Global optimization vs. local optimization

==== Product management
* Scrum
* Contrasted to project management

==== IT infrastructure
* Cloud
* Web-scale IT

==== IT applications
* Continuous delivery pipeline

==== Work management
* Kanban
* Contrasted to project management

==== Operations management

=== Principles & context

==== Organizational development
* Spectrum of organizational models
* Purely functional to purely skunkworks
* The problem of specialization

==== Product flow
* Product development versus production
* The need for fast feedback
* The problem of invisible WIP
* Decision making techniques in enabling fast flow of work
* Software and operations architecture to sustain fast flow and experimentation
* Advanced change theory
* DevOps metrics and measurement
* Continuous monitoring procedures
* The theory of constraints
* Queuing theory

various DevOps test architecture and patterns. You will explore several structured DevOps approaches that guide decision making in this field. DevOps student teams will understand and implement policies and procedures necessary to engage with customers, and to continually shape and reshape their requirements with customer satisfaction in mind. Students will learn the need for shared goals and visibility and cross-team dependencies that contribute to building solutions.
Topics include:

* Processes in automation




== Thoughts on course mappings

* IT infrastructure (SEIS660)
As currently structured, this course could serve as a survey for the certificate, but students will want more hands-on. Span is currently very broad.

* Java programming
If this course were adapted to use a DevOps pipeline, it could provide the focused hands-on needed.

* IT requirements

* IT project management

Notes from University of Washington program manager discussion - why they cancelled.

- Premature market entry
- DevOps is "culture" & hard to teach
- Competition from tailored internal programs
- Semester-long working professional approach is limited - people favor more intense learnings
