= Devops Certificate Approach

== Objectives
By taking the courses comprising this certificate, students will learn DevOps fundamentals including its vision, culture, workflow, monitoring methods and tools. Students will take these concepts and see how they relate to software design and construction, automated testing, continuous integration and build and deployment management with modern, automated pipelines.

== Topics

=== Product management
* Contrasted to project management
* Scrum
* Product development versus production
* The need for fast feedback
* Decision making techniques in enabling fast flow of work
* Software and operations architecture to sustain fast flow and experimentation
* DevOps metrics and measurement
* The theory of constraints
* Queuing theory

=== IT infrastructure
* Cloud
* Web-scale IT

=== IT applications
* Automated testing
* A/B testing
* Continuous delivery pipeline

=== Work management
* Kanban
* The problem of invisible WIP

=== Operations management
* Production monitoring
* Advanced change theory

=== Organizational development
* Global optimization vs. local optimization
* Spectrum of organizational models
* Purely functional to purely skunkworks
* The problem of specialization


== Thoughts on course mappings

=== SEIS 610 SEng Method
Iterative & incremental is discussed
increase practical source control?
Gathering requirement, designing, implementing
Maintenance

=== SEIS 636 IT requirements
To support the certificate, This course could include more on product  management, which is becoming the primary way in which Agile organizations are structed.

=== SEIS 625 IT project management
To support the certificate, needs a strong Scrum component.

=== SEIS 626 Quality management
To support the certificate, should include a strong test-driven design component.

It might be valuable if this class in particular would share the same simulation infrastructure as SEIS660. The lab server there is already set up with a full test-driven development pipeline.

=== SEIS 660 IT infrastructure
As currently structured, this course could serve as a survey for the certificate, but students will want more hands-on. Span is currently very broad. The latter lectures are more about process & enterprise level concerns, perhaps less relevant.

=== Java programming
If this course were adapted to use the SEIS660 DevOps pipeline, it could provide the focused hands-on needed.

=== U of WA DevOps certificate (cancelled)

Notes from University of Washington program manager (Lalitha Subramaniam) discussion - why they cancelled.

- Premature market entry
- DevOps is "culture" & hard to teach
- Competition from tailored internal programs
- Semester-long working professional approach is limited - people favor more intense learnings
