= Minnesota Agile Study Group

The Agile movement is one of the most significant movements in the history of information technology and computing. Its influence is extending well beyond its IT origins into management more broadly. Information technology is an increasing part of all products (e.g. the Internet of Things), and so Agile approaches are seen increasingly throughout product management. Lean has been a major influence on Agile, and these two movements continue to converge and interact. Agile approaches to starting new companies are gaining favor as well.

The purpose of this group is to study and develop an educational response to the Agile movement, in the interests of supporting Minnesota educators and industry partners. This group welcomes all Minnesota educators, industry practitioners, students, and anyone else who is interested.

Minnesota has a rich history in computing footnote:[“Minnesota’s Hidden History in Computing,” Charles Babbage Institute, University of Minnesota, http://www.cbi.umn.edu/resources/MHHC/.], as the cradle of many significant IT companies: Control Data, Univac, Honeywell, Cray, IBM Rochester, and more. However, more recently, Minnesota is in decline as an innovation center. The state is losing young workers and critical innovation centers to the West Coast footnote:[“Minnesota's youth exodus spells trouble ahead for labor force,” Minnesota Star Tribune, April 18, 2015, http://www.startribune.com/minnesota-s-youth-exodus-spells-trouble-ahead-for-labor-force/300549671/ ; “Target opens office in heart of Silicon Valley,” Minnesota Star Tribune, August 5, 2014, http://www.startribune.com/target-opens-office-in-heart-of-silicon-valley/269916971/;
“Best Buy is opening a tech office in Seattle,” Minnesota Star Tribune, February 19, 2015, http://www.startribune.com/best-buy-opening-seattle-tech-office-hiring-50/292423651/
].

Even so, the state continues to support an above-average concentration of large corporate headquarters (Target, Best Buy, United Health Group, Cargill, General Mills, 3M, SuperValu, EcoLab and many more), medical technology firms (Medtronic, St. Jude) as well as significant technology design, operations, and services centers of non-Minnesota firms (Unisys, Wells Fargo, Symantec, Seagate, Boston Scientific, etc).

We are already seeing disruptions in the workforce stemming from Lean and Agile management approaches to IT. A major Minnesota company recently let hundreds of traditionally positioned IT professionals go, while simultaneously opening up dozens of “DevOps” positions. Other such anecdotes are increasingly heard. Minnesota educators have a responsibility to respond to these trends. There is a large workforce in need of assistance.

New curricula are called for, and an increasing degree of collaboration across Minnesota educational institutions, perhaps reminiscent of the old https://en.wikipedia.org/wiki/MECC[Minnesota Educational Computing Consortium].

We would like to hear from all Minnesota educators interested in the following:

* Management information systems and IT management
* Agile methods, including their broader acceptance and influence on enterprise thinking
* Lean product development, especially when including a major IT component.
* Enterprise "digital transformation"
* Lean Startup philosophy
* Scrum, Kanban, and related methods
* Continuous delivery, DevOps, and related practices
* Agile and Lean theories

We believe that there is clearly a new emerging model of information technology delivery. See
